### ISSUE TITLE
When loaded into a fresh env, anndata fails to be able to import in python with current build

### ISSUE THREAD

**Issue by astrovsky01** [conda-forge/anndata-feedstock#2]
New env create, loaded packages include:

```console
$ conda list
anndata=0.6.19 scanpy=1.4 loompy=2.0.17
```

Gives following error on import anndata:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexanderostrovsky/anaconda3/envs/my_env_name/lib/python3.6/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData
  File "/Users/alexanderostrovsky/anaconda3/envs/my_env_name/lib/python3.6/site-packages/anndata/base.py", line 21, in <module>
    from scipy.sparse.sputils import IndexMixin
ImportError: cannot import name 'IndexMixin'
```

**Comment by flying-sheep** [comment]
The current version of anndata is [![0.6.22.post1](https://img.shields.io/conda/vn/conda-forge/anndata.svg)](https://anaconda.org/conda-forge/anndata), you should update it.
